// Mocks generated by Mockito 5.4.6 from annotations
// in vocatus/test/app/modules/disciplines/disciplines_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:vocatus/app/models/discipline.dart' as _i2;
import 'package:vocatus/app/repositories/disciplines/discipline_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDiscipline_0 extends _i1.SmartFake implements _i2.Discipline {
  _FakeDiscipline_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DisciplineRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDisciplineRepository extends _i1.Mock
    implements _i3.DisciplineRepository {
  MockDisciplineRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Discipline> createDiscipline(_i2.Discipline? discipline) =>
      (super.noSuchMethod(
            Invocation.method(#createDiscipline, [discipline]),
            returnValue: _i4.Future<_i2.Discipline>.value(
              _FakeDiscipline_0(
                this,
                Invocation.method(#createDiscipline, [discipline]),
              ),
            ),
          )
          as _i4.Future<_i2.Discipline>);

  @override
  _i4.Future<List<_i2.Discipline>> readDisciplines() =>
      (super.noSuchMethod(
            Invocation.method(#readDisciplines, []),
            returnValue: _i4.Future<List<_i2.Discipline>>.value(
              <_i2.Discipline>[],
            ),
          )
          as _i4.Future<List<_i2.Discipline>>);

  @override
  _i4.Future<void> updateDiscipline(_i2.Discipline? discipline) =>
      (super.noSuchMethod(
            Invocation.method(#updateDiscipline, [discipline]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteDiscipline(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDiscipline, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
